
const Translations = {
    en: {
      title: "The True Phonetics Story",
      paragraph1: "Development of the True Phonetics app began on the 10th of May 2024 when Australian polyglot Alex Penman hired Indian coding teacher Siddharth Bisht to help him build out his idea for the perfect way to learn pronunciation. Eventually, Siddharth came to believe that this app would bring real value to people's lives in a way that has never been done before and would therefore be successful. At this point, he was already an experienced full-stack, cross-platform developer who had helped launch many startups. Therefore, when Alex proposed that they stop being student and teacher and become founders of a technology company, Siddharth eagerly accepted.",
      paragraph2: "True Phonetics Pty. Ltd. was incorporated as an Australian company on the 5th of July 2024 with Siddharth Bisht as CTO and Alex Penman as CEO, but its true origins stretch back to 2019 when Alex began teaching the International Phonetic Alphabet (IPA) to his English language students. With time, he became completely fluent in reading the IPA and reading and writing a version of the IPA which he had modified and would eventually come to be called the 'New Phonetic Model'. Alex had to modify the IPA in order to write hundreds of pages phonetically in different accents. It was necessary because the normal IPA was far too inaccurate to be used for mass production of phonetic texts. In contrast, the NPM he developed was 100% accurate in describing the way Alex spoke English, although it was far less legible and logical than it could be.",
      paragraph3: "As well as simplifying the phonetic alphabet, Alex also understood its value in a way that many don't. He already understood the value of a phonetic alphabet when learning a foreign language, as he had taught himself the French phonetic alphabet and experienced firsthand how the human mind can grasp and remember images better than raw sounds. Therefore, when you know an image associated with a sound, you can build an understanding and awareness of that sound in your mind, allowing you to hear it better and, if you practice, produce it better. Furthermore, Alex understood that the English IPA had value for him as an English speaker because it allows one to write accents. Through research and playing around with sounds, he came to realise just how easy it is to speak in a different English accent without making any new sounds; just by making the same sounds as usual, but in different places.",
      paragraph4: "Having already learned to speak French, Spanish, Italian, German, and Portuguese to at least conversational ease, Alex applied his language learning techniques towards learning to speak English with different accents. One of the reasons that Alex had been so successful as a polyglot was his lack of self-consciousness in speaking to himself aloud. Just as he had learned to speak a lot of Portuguese just by applying different pronunciation patterns to words he already knew, Alex applied pronunciation patterns to achieve different accents and practiced until fluency.",
      paragraph5: "Alex spent years sitting on his unusually advanced phonetic knowledge and ability. Then, at the start of May 2024, he was making a video exposing all the problems with the IPA that virtually all IPA teachers make online when suddenly he had a brainwave: an app! An app in which people learn to write, read, and speak the phonetic alphabet in different accents! Now, not only did he have the best phonetic alphabet and the best reason to learn it, he also had the perfect way to teach it.",
      paragraph6: "With the help of ChatGPT, he quickly built a prototype in HTML, CSS, and JavaScript for the web, but he came to realize that this app needed to be for mobile as well. He did some research, decided to build it in React Native, and went looking for a React Native teacher. He found Siddharth, who was the first teacher he came across who could build anything he wanted, and True Phonetics was born."
    },
    hi: { // Hindi
      title: "True Phonetics की कहानी",
      paragraph1: "True Phonetics ऐप का विकास 10 मई 2024 को शुरू हुआ जब ऑस्ट्रेलियाई बहुभाषाविद एलेक्स पेनमैन ने भारतीय कोडिंग शिक्षक सिद्धार्थ बिष्ट को अपने उच्चारण सीखने के लिए सही तरीके के विचार को विकसित करने में मदद करने के लिए नियुक्त किया। अंततः, सिद्धार्थ को विश्वास हो गया कि यह ऐप लोगों के जीवन में वास्तविक मूल्य लाएगा जिस तरह से पहले कभी नहीं किया गया और इसलिए यह सफल होगा। इस समय, वह पहले से ही एक अनुभवी फुल-स्टैक , क्रॉस-प्लेटफ़ॉर्म डेवलपर था जिसने कई स्टार्टअप लॉन्च करने में मदद की थी। इसलिए, जब एलेक्स ने प्रस्तावित किया कि वे छात्र और शिक्षक बनना बंद करें और एक तकनीकी कंपनी के संस्थापक बनें, तो सिद्धार्थ ने खुशी-खुशी स्वीकार कर लिया।",
      paragraph2: "True Phonetics Pty. Ltd. 5 जुलाई 2024 को एक ऑस्ट्रेलियाई कंपनी के रूप में स्थापित की गई, जिसमें सिद्धार्थ बिष्ट CTO और एलेक्स पेनमैन CEO थे, लेकिन इसकी असली उत्पत्ति 2019 में वापस जाती है जब एलेक्स ने अपने अंग्रेजी भाषा के छात्रों को अंतर्राष्ट्रीय ध्वन्यात्मक वर्णमाला (IPA) पढ़ाना शुरू किया। समय के साथ, वह IPA पढ़ने और एक संस्करण को पढ़ने और लिखने में पूरी तरह से धाराप्रवाह हो गया जिसे उसने संशोधित किया था और जिसे अंततः 'न्यू फोनेटिक मॉडल' कहा जाएगा। एलेक्स को विभिन्न लहजों में ध्वन्यात्मक रूप से सैकड़ों पृष्ठ लिखने के लिए IPA को संशोधित करना पड़ा। यह आवश्यक था क्योंकि सामान्य IPA ध्वन्यात्मक पाठों के बड़े पैमाने पर उत्पादन के लिए उपयोग करने के लिए बहुत असंगत था। इसके विपरीत, NPM जो उसने विकसित किया था, वह 100% सटीक था जो एलेक्स के अंग्रेजी बोलने के तरीके का वर्णन करता था, हालांकि यह पढ़ने में बहुत कम स्पष्ट और तार्किक था।",
      paragraph3: "ध्वन्यात्मक वर्णमाला को सरल बनाने के साथ-साथ, एलेक्स ने इसकी मूल्य को भी समझा जिसे कई लोग नहीं समझते। जब वह एक विदेशी भाषा सीख रहा था, तब उसने पहले ही ध्वन्यात्मक वर्णमाला के मूल्य को समझ लिया था, क्योंकि उसने फ्रेंच ध्वन्यात्मक वर्णमाला को स्वयं सीखा था और अनुभव किया था कि मानव मस्तिष्क छवियों को कच्चे ध्वनियों की तुलना में बेहतर समझ और याद कर सकता है। इसलिए, जब आप एक ध्वनि से संबंधित छवि जानते हैं, तो आप अपने मन में उस ध्वनि की समझ और जागरूकता बना सकते हैं, जिससे आप इसे बेहतर सुन सकते हैं और यदि आप अभ्यास करते हैं, तो इसे बेहतर तरीके से उत्पन्न कर सकते हैं। इसके अलावा, एलेक्स ने समझा कि अंग्रेजी IPA उसके लिए एक अंग्रेजी बोलने वाले के रूप में मूल्यवान था क्योंकि यह किसी को लहजे लिखने की अनुमति देता है। अनुसंधान और ध्वनियों के साथ खेलने के माध्यम से, उसने यह महसूस किया कि बिना किसी नए ध्वनियों को बनाए, एक अलग अंग्रेजी लहजे में बोलना कितना आसान है; बस वही ध्वनियाँ बनाकर, लेकिन अलग-अलग स्थानों पर।",
      paragraph4: "पहले से ही फ्रेंच, स्पेनिश, इटालियन, जर्मन, और पुर्तगाली को कम से कम बातचीत की सुविधा के साथ बोलना सीखने के बाद, एलेक्स ने विभिन्न लहजों के साथ अंग्रेजी बोलने के लिए अपनी भाषा सीखने की तकनीकों को लागू किया। एलेक्स के बहुभाषाविद के रूप में सफल होने के पीछे एक कारण यह था कि वह खुद से जोर से बोलने में आत्म-सचेत नहीं थे। जैसे उसने पहले से ही जाने गए शब्दों पर विभिन्न उच्चारण पैटर्न लागू करके बहुत सारा पुर्तगाली बोलना सीखा, एलेक्स ने विभिन्न लहजों को प्राप्त करने के लिए उच्चारण पैटर्न लागू किए और धाराप्रवाहित होने तक अभ्यास किया।",
      paragraph5: "एलेक्स ने अपने असामान्य रूप से उन्नत ध्वन्यात्मक ज्ञान और क्षमता पर वर्षों बिताए। फिर, मई 2024 की शुरुआत में, वह एक वीडियो बना रहा था जिसमें वह IPA की सभी समस्याओं को उजागर कर रहा था जो लगभग सभी IPA शिक्षक ऑनलाइन करते हैं, जब अचानक उसे एक विचार आया: एक ऐप! एक ऐसा ऐप जिसमें लोग विभिन्न लहजों में ध्वन्यात्मक वर्णमाला को लिखना, पढ़ना और बोलना सीखें! अब, न केवल उसके पास सबसे अच्छा ध्वन्यात्मक वर्णमाला और इसे सीखने का सबसे अच्छा कारण था, बल्कि उसे इसे सिखाने का सही तरीका भी मिल गया था।",
      paragraph6: "ChatGPT की मदद से, उसने जल्दी से HTML, CSS, और JavaScript में वेब के लिए एक प्रोटोटाइप बनाया, लेकिन उसे एहसास हुआ कि यह ऐप मोबाइल के लिए भी होना चाहिए। उसने कुछ शोध किया, इसे React Native में बनाने का निर्णय लिया, और एक React Native शिक्षक की तलाश में निकल पड़ा। उसे सिद्धार्थ मिला, जो पहला शिक्षक था जिसे उसने देखा जो उसकी इच्छ ानुसार कुछ भी बना सकता था, और इस तरह सच्ची ध्वन्यात्मकता का जन्म हुआ।"
    },
    es: { // Spanish
      title: "La Historia de True Phonetics",
      paragraph1: "El desarrollo de la aplicación True Phonetics comenzó el 10 de mayo de 2024 cuando el poliglota australiano Alex Penman contrató al profesor de codificación indio Siddharth Bisht para ayudarlo a desarrollar su idea sobre la forma perfecta de aprender pronunciación. Con el tiempo, Siddharth llegó a creer que esta aplicación traería un valor real a la vida de las personas de una manera que nunca se había hecho antes y, por lo tanto, sería exitosa. En ese momento, ya era un desarrollador full-stack y multiplataforma experimentado que había ayudado a lanzar muchas startups. Por lo tanto, cuando Alex propuso que dejaran de ser estudiante y profesor y se convirtieran en fundadores de una empresa tecnológica, Siddharth aceptó con entusiasmo.",
      paragraph2: "True Phonetics Pty. Ltd. se incorporó como una empresa australiana el 5 de julio de 2024, con Siddharth Bisht como CTO y Alex Penman como CEO, pero sus verdaderos orígenes se remontan a 2019, cuando Alex comenzó a enseñar el Alfabeto Fonético Internacional (IPA) a sus estudiantes de inglés. Con el tiempo, se volvió completamente fluido en la lectura del IPA y en la lectura y escritura de una versión del IPA que había modificado y que eventualmente se llamaría 'Nuevo Modelo Fonético'. Alex tuvo que modificar el IPA para escribir cientos de páginas fonéticamente en diferentes acentos. Era necesario porque el IPA normal era demasiado inexacto para ser utilizado en la producción masiva de textos fonéticos. En contraste, el NPM que desarrolló era 100% preciso al describir la forma en que Alex hablaba inglés, aunque era mucho menos legible y lógico de lo que podría ser.",
      paragraph3: "Además de simplificar el alfabeto fonético, Alex también entendió su valor de una manera que muchos no lo hacen. Ya entendía el valor de un alfabeto fonético al aprender un idioma extranjero, ya que se había enseñado a sí mismo el alfabeto fonético francés y había experimentado de primera mano cómo la mente humana puede captar y recordar imágenes mejor que los sonidos crudos. Por lo tanto, cuando conoces una imagen asociada con un sonido, puedes construir una comprensión y conciencia de ese sonido en tu mente, lo que te permite escucharlo mejor y, si practicas, producirlo mejor. Además, Alex entendió que el IPA en inglés tenía valor para él como hablante de inglés porque permite escribir acentos. A través de la investigación y jugando con sonidos, se dio cuenta de lo fácil que es hablar con un acento inglés diferente sin hacer nuevos sonidos; simplemente haciendo los mismos sonidos de siempre, pero en diferentes lugares.",
      paragraph4: "Después de haber aprendido a hablar francés, español, italiano, alemán y portugués con al menos facilidad conversacional, Alex aplicó sus técnicas de aprendizaje de idiomas para aprender a hablar inglés con diferentes acentos. Una de las razones por las que Alex había tenido tanto éxito como poliglota era su falta de autoconciencia al hablar en voz alta consigo mismo. Así como había aprendido a hablar mucho portugués simplemente aplicando diferentes patrones de pronunciación a palabras que ya conocía, Alex aplicó patrones de pronunciación para lograr diferentes acentos y practicó hasta alcanzar la fluidez.",
      paragraph5: "Alex pasó años sentándose sobre su inusualmente avanzado conocimiento y habilidad fonética. Luego, a principios de mayo de 2024, estaba haciendo un video exponiendo todos los problemas con el IPA que prácticamente todos los profesores de IPA hacen en línea cuando de repente tuvo una idea brillante: ¡una aplicación! ¡Una aplicación en la que las personas aprenden a escribir, leer y hablar el alfabeto fonético en diferentes acentos! Ahora, no solo tenía el mejor alfabeto fonético y la mejor razón para aprenderlo, sino que también tenía la forma perfecta de enseñarlo.",
      paragraph6: "Con la ayuda de ChatGPT, rápidamente construyó un prototipo en HTML, CSS y JavaScript para la web, pero se dio cuenta de que esta aplicación también necesitaba ser para móviles. Hizo algunas investigaciones, decidió construirla en React Native y salió en busca de un profesor de React Native. Encontró a Siddharth, quien fue el primer profesor que encontró que podía construir cualquier cosa que quisiera, y así nació True Phonetics."
    },
    fr: { // French
      title: "L'Histoire de True Phonetics",
      paragraph1: "Le développement de l'application True Phonetics a commencé le 10 mai 2024 lorsque le polyglotte australien Alex Penman a engagé le professeur de codage indien Siddharth Bisht pour l'aider à développer son idée de la manière parfaite d'apprendre la prononciation. Finalement, Siddharth en est venu à croire que cette application apporterait une réelle valeur à la vie des gens d'une manière qui n'avait jamais été faite auparavant et serait donc couronnée de succès. À ce moment-là, il était déjà un développeur full-stack et multiplateforme expérimenté qui avait aidé à lancer de nombreuses startups. Par conséquent, lorsque Alex a proposé qu'ils cessent d'être étudiant et professeur et deviennent fondateurs d'une entreprise technologique, Siddharth a accepté avec enthousiasme.",
      paragraph2: "True Phonetics Pty. Ltd. a été constituée en tant qu'entreprise australienne le 5 juillet 2024, avec Siddharth Bisht en tant que CTO et Alex Penman en tant que CEO, mais ses véritables origines remontent à 2019, lorsque Alex a commencé à enseigner l'Alphabet Phonétique International (API) à ses étudiants en anglais. Avec le temps, il est devenu complètement fluide dans la lecture de l'API et dans la lecture et l'écriture d'une version de l'API qu'il avait modifiée et qui serait finalement appelée le 'Nouveau Modèle Phonétique'. Alex a dû modifier l'API pour écrire des centaines de pages phonétiquement dans différents accents. C'était nécessaire car l'API normale était beaucoup trop inexacte pour être utilisée pour la production de masse de textes phonétiques. En revanche, le NMP qu'il a développé était 100 % précis pour décrire la façon dont Alex parlait anglais, bien qu'il soit beaucoup moins lisible et logique qu'il ne pourrait l'être.",
      paragraph3: "En plus de simplifier l'alphabet phonétique, Alex a également compris sa valeur d'une manière que beaucoup ne font pas. Il comprenait déjà la valeur d'un alphabet phonétique lorsqu'il apprenait une langue étrangère, car il s'était enseigné lui-même l'alphabet phonétique français et avait expérimenté de première main comment l'esprit humain peut saisir et se souvenir des images mieux que des sons bruts. Par conséquent, lorsque vous connaissez une image associée à un son, vous pouvez construire une compréhension et une conscience de ce son dans votre esprit, ce qui vous permet de mieux l'entendre et, si vous pratiquez, de mieux le produire. De plus, Alex a compris que l'API anglaise avait de la valeur pour lui en tant que locuteur anglais car elle permet d'écrire des accents. Grâce à la recherche et à des jeux avec des sons, il a réalisé à quel point il est facile de parler avec un accent anglais différent sans produire de nouveaux sons ; simplement en produisant les mêmes sons que d'habitude, mais à des endroits différents.",
      paragraph4: "Ayant déjà appris à parler français, espagnol, italien, allemand et portugais avec au moins une aisance conversationnelle, Alex a appliqué ses techniques d'apprentissage des langues pour apprendre à parler anglais avec différents accents. L'une des raisons pour lesquelles Alex avait eu tant de succès en tant que polyglotte était son absence de conscience de soi en parlant à voix haute. Tout comme il avait appris à parler beaucoup de portugais simplement en appliquant différents modèles de prononciation à des mots qu'il connaissait déjà, Alex a appliqué des modèles de prononciation pour obtenir différents accents et a pratiqué jusqu'à atteindre la fluidité.",
      paragraph5: "Alex a passé des années à s'appuyer sur ses connaissances et compétences phonétiques exceptionnellement avancées. Puis, au début de mai 2024, il réalisait une vidéo exposant tous les problèmes de l'API que pratiquement tous les enseignants d'API rencontrent en ligne quand soudain il a eu une idée brillante : une application ! Une application dans laquelle les gens apprennent à écrire, lire et parler l'alphabet phonétique dans différents accents ! Maintenant, non seulement il avait le meilleur alphabet phonétique et la meilleure raison de l'apprendre, mais il avait aussi la manière parfaite de l'enseigner.",
      paragraph6: "Avec l'aide de ChatGPT, il a rapidement construit un prototype en HTML, CSS et JavaScript pour le web, mais il s'est rendu compte que cette application devait également être mobile. Il a fait quelques recherches, a décidé de la construire en React Native et est parti à la recherche d'un professeur de React Native. Il a trouvé Siddharth, qui était le premier professeur qu'il a rencontré capable de construire tout ce qu'il voulait, et ainsi True Phonetics est né."
    },
    de: { // German
      title: "Die Geschichte von True Phonetics",
      paragraph1: "Die Entwicklung der True Phonetics-App begann am 10. Mai 2024, als der australische Polyglott Alex Penman den indischen Programmierlehrer Siddharth Bisht engagierte, um ihm zu helfen, seine Idee für den perfekten Weg zum Erlernen der Aussprache zu entwickeln. Schließlich kam Siddharth zu dem Glauben, dass diese App den Menschen auf eine Weise echten Wert bringen würde, wie es zuvor noch nie geschehen war, und daher erfolgreich sein würde. Zu diesem Zeitpunkt war er bereits ein erfahrener Full-Stack-Entwickler, der vielen Startups beim Start geholfen hatte. Daher akzeptierte Siddharth begeistert, als Alex vorschlug, dass sie aufhören sollten, Schüler und Lehrer zu sein, und stattdessen Gründer eines Technologieunternehmens werden sollten.",
      paragraph2: "True Phonetics Pty. Ltd. wurde am 5. Juli 2024 als australisches Unternehmen gegründet, mit Siddharth Bisht als CTO und Alex Penman als CEO, aber ihre wahren Ursprünge reichen bis ins Jahr 2019 zurück, als Alex begann, das Internationale Phonetische Alphabet (IPA) seinen Englischschülern beizubringen. Mit der Zeit wurde er vollständig fließend im Lesen des IPA und im Lesen und Schreiben einer Version des IPA, die er modifiziert hatte und die schließlich als 'Neues Phonetisches Modell' bezeichnet werden sollte. Alex musste das IPA modifizieren, um Hunderte von Seiten phonetisch in verschiedenen Akzenten zu schreiben. Dies war notwendig, da das normale IPA viel zu ungenau war, um für die Massenproduktion phonetischer Texte verwendet zu werden. Im Gegensatz dazu war das NPM, das er entwickelte, 100 % genau in der Beschreibung der Art und Weise, wie Alex Englisch sprach, obwohl es viel weniger lesbar und logisch war, als es sein könnte.",
      paragraph3: "Neben der Vereinfachung des phonetischen Alphabets verstand Alex auch dessen Wert auf eine Weise, die viele nicht tun. Er verstand bereits den Wert eines phonetischen Alphabets beim Erlernen einer Fremdsprache, da er sich selbst das französische phonetische Alphabet beigebracht hatte und aus erster Hand erfahren hatte, wie der menschliche Geist Bilder besser erfassen und sich merken kann als rohe Klänge. Daher kann man, wenn man ein Bild mit einem Klang verbindet, ein Verständnis und Bewusstsein für diesen Klang im eigenen Geist aufbauen, was es einem ermöglicht, ihn besser zu hören und, wenn man übt, ihn besser zu produzieren. Darüber hinaus verstand Alex, dass das englische IPA für ihn als Englischsprecher von Wert war, da es einem erlaubt, Akzente zu schreiben. Durch Forschung und das Spielen mit Klängen erkannte er, wie einfach es ist, mit einem anderen englischen Akzent zu sprechen, ohne neue Klänge zu erzeugen; einfach indem man die gleichen Klänge wie gewohnt, aber an anderen Stellen macht.",
      paragraph4: "Nachdem er bereits gelernt hatte, Französisch, Spanisch, Italienisch, Deutsch und Portugiesisch mindestens auf Konversationsniveau zu sprechen, wandte Alex seine Sprachlerntechniken an, um Englisch mit verschiedenen Akzenten zu lernen. Einer der Gründe, warum Alex als Polyglott so erfolgreich war, war seine mangelnde Selbstbewusstheit beim lauten Sprechen mit sich selbst. So wie er viel Portugiesisch gelernt hatte, indem er einfach verschiedene Aussprachemuster auf Wörter anwendete, die er bereits kannte, wandte Alex Aussprachemuster an, um verschiedene Akzente zu erreichen und übte, bis er fließend war.",
      paragraph5: "Alex verbrachte Jahre damit, auf seinem ungewöhnlich fortgeschrittenen phonetischen Wissen und Können zu sitzen. Dann, zu Beginn des Mai 2024, machte er ein Video, in dem er alle Probleme mit dem IPA aufdeckte, die praktisch alle IPA-Lehrer online machen, als ihm plötzlich eine geniale Idee kam: eine App! Eine App, in der Menschen lernen, das phonetische Alphabet in verschiedenen Akzenten zu schreiben, zu lesen und zu sprechen! Jetzt hatte er nicht nur das beste phonetische Alphabet und den besten Grund, es zu lernen, sondern auch den perfekten Weg, es zu lehren.",
      paragraph6: "Mit Hilfe von ChatGPT baute er schnell einen Prototyp in HTML, CSS und JavaScript für das Web, erkannte jedoch, dass diese App auch für mobile Geräte sein musste. Er machte einige Recherchen, entschied sich, es in React Native zu bauen, und machte sich auf die Suche nach einem React Native-Lehrer. Er fand Siddharth, der der erste Lehrer war, den er traf, der alles bauen konnte, was er wollte, und so wurde True Phonetics geboren."
    },
    
    pt: { // Portuguese
      title: "A História do True Phonetics",
      paragraph1: "O desenvolvimento do aplicativo True Phonetics começou em 10 de maio de 2024, quando o poliglota australiano Alex Penman contratou o professor de programação indiano Siddharth Bisht para ajudá-lo a desenvolver sua ideia sobre a maneira perfeita de aprender pronúncia. Com o tempo, Siddharth passou a acreditar que este aplicativo traria um valor real para a vida das pessoas de uma forma que nunca havia sido feita antes e, portanto, seria bem-sucedido. Naquele momento, ele já era um desenvolvedor full-stack e multiplataforma experiente que havia ajudado a lançar muitas startups. Portanto, quando Alex propôs que parassem de ser aluno e professor e se tornassem fundadores de uma empresa de tecnologia, Siddharth aceitou com entusiasmo.",
      paragraph2: "True Phonetics Pty. Ltd. foi incorporada como uma empresa australiana em 5 de julho de 2024, com Siddharth Bisht como CTO e Alex Penman como CEO, mas suas verdadeiras origens remontam a 2019, quando Alex começou a ensinar o Alfabeto Fonético Internacional (IPA) a seus alunos de inglês. Com o tempo, ele se tornou completamente fluente na leitura do IPA e na leitura e escrita de uma versão do IPA que ele havia modificado e que eventualmente seria chamada de 'Novo Modelo Fonético'. Alex teve que modificar o IPA para escrever centenas de páginas foneticamente em diferentes sotaques. Isso era necessário porque o IPA normal era muito impreciso para ser usado na produção em massa de textos fonéticos. Em contraste, o NPM que ele desenvolveu era 100% preciso ao descrever a maneira como Alex falava inglês, embora fosse muito menos legível e lógico do que poderia ser.",
      paragraph3: "Além de simplificar o alfabeto fonético, Alex também entendeu seu valor de uma maneira que muitos não fazem. Ele já entendia o valor de um alfabeto fonético ao aprender uma língua estrangeira, pois havia ensinado a si mesmo o alfabeto fonético francês e experimentado em primeira mão como a mente humana pode captar e lembrar imagens melhor do que sons brutos. Portanto, quando você conhece uma imagem associada a um som, pode construir uma compreensão e consciência desse som em sua mente, permitindo que você o ouça melhor e, se praticar, o produza melhor. Além disso, Alex entendeu que o IPA em inglês tinha valor para ele como falante de inglês porque permite escrever sotaques. Através de pesquisa e brincando com sons, ele percebeu o quão fácil é falar com um sotaque inglês diferente sem fazer novos sons; apenas fazendo os mesmos sons de sempre, mas em lugares diferentes.",
      paragraph4: "Depois de já ter aprendido a falar francês, espanhol, italiano, alemão e português com pelo menos facilidade conversacional, Alex aplicou suas técnicas de aprendizado de idiomas para aprender a falar inglês com diferentes sotaques. Uma das razões pelas quais Alex teve tanto sucesso como poliglota foi sua falta de autoconsciência ao falar em voz alta consigo mesmo. Assim como ele aprendeu a falar muito português apenas aplicando diferentes padrões de pronúncia a palavras que já conhecia, Alex aplicou padrões de pronúncia para alcançar diferentes sotaques e praticou até a fluência.",
      paragraph5: "Alex passou anos sentado sobre seu conhecimento e habilidade fonética incomumente avançados. Então, no início de maio de 2024, ele estava fazendo um vídeo expondo todos os problemas com o IPA que praticamente todos os professores de IPA fazem online quando, de repente, teve uma ideia brilhante: um aplicativo! Um aplicativo no qual as pessoas aprendem a escrever, ler e falar o alfabeto fonético em diferentes sotaques! Agora, ele não apenas tinha o melhor alfabeto fonético e a melhor razão para aprendê-lo, mas também tinha a maneira perfeita de ensiná-lo.",
      paragraph6: "Com a ajuda do ChatGPT, ele rapidamente construiu um protótipo em HTML, CSS e JavaScript para a web, mas percebeu que este aplicativo também precisava ser para dispositivos móveis. Ele fez algumas pesquisas, decidiu construí-lo em React Native e saiu em busca de um professor de React Native. Ele encontrou Siddharth, que foi o primeiro professor que encontrou que poderia construir qualquer coisa que quisesse, e assim nasceu o True Phonetics."
    },
    ru: { // Russian
      title: "История True Phonetics",
      paragraph1: "Разработка приложения True Phonetics началась 10 мая 2024 года, когда австралийский полиглот Алекс Пенман нанял индийского преподавателя программирования Сиддхарта Бишта, чтобы помочь ему реализовать его идею о совершенном способ учить произношение. В конечном итоге Сиддхарт пришел к выводу, что это приложение принесет реальную ценность в жизни людей таким образом, как это никогда не делалось ранее, и, следовательно, будет успешным. На тот момент он уже был опытным разработчиком полного стека и кроссплатформенным разработчиком, который помогал запускать множество стартапов. Поэтому, когда Алекс предложил им прекратить быть студентом и учителем и стать основателями технологической компании, Сиддхарт с радостью согласился.",
      paragraph2: "True Phonetics Pty. Ltd. была зарегистрирована как австралийская компания 5 июля 2024 года, с Сиддхартом Биштом в роли CTO и Алексом Пенманом в роли CEO, но ее истинные корни уходят в 2019 год, когда Алекс начал преподавать Международный фонетический алфавит (IPA) своим студентам английского языка. Со временем он стал полностью свободно читать IPA и читать и писать версию IPA, которую он модифицировал и которая в конечном итоге будет называться 'Новая фонетическая модель'. Алексу пришлось модифицировать IPA, чтобы написать сотни страниц фонетически на разных акцентах. Это было необходимо, потому что обычный IPA был слишком неточным для массового производства фонетических текстов. В отличие от этого, NPM, который он разработал, был на 100% точным в описании того, как Алекс говорил по-английски, хотя он был гораздо менее читаемым и логичным, чем мог бы быть.",
      paragraph3: "Помимо упрощения фонетического алфавита, Алекс также понимал его ценность так, как многие этого не делают. Он уже понимал ценность фонетического алфавита при изучении иностранного языка, так как сам изучал французский фонетический алфавит и на собственном опыте узнал, как человеческий разум может лучше воспринимать и запоминать образы, чем сырые звуки. Поэтому, когда вы знаете образ, связанный со звуком, вы можете построить понимание и осознание этого звука в своем сознании, что позволяет вам лучше его слышать и, если вы практикуете, лучше его произносить. Более того, Алекс понимал, что английский IPA имеет ценность для него как для носителя английского языка, потому что он позволяет записывать акценты. Путем исследований и экспериментов со звуками он пришел к осознанию того, как легко говорить с другим английским акцентом, не создавая новых звуков; просто произнося те же звуки, что и обычно, но в других местах.",
      paragraph4: "Уже научившись говорить на французском, испанском, итальянском, немецком и португальском на хотя бы разговорном уровне, Алекс применил свои техники изучения языков для изучения английского с различными акцентами. Одной из причин, по которой Алекс был так успешен как полиглот, была его отсутствие самосознания при разговоре с самим собой вслух. Так же, как он научился говорить на португальском, просто применяя различные паттерны произношения к словам, которые он уже знал, Алекс применял паттерны произношения, чтобы достичь различных акцентов и практиковался до достижения беглости.",
      paragraph5: "Алекс провел годы, сидя на своем необычно продвинутом фонетическом знании и умении. Затем, в начале мая 2024 года, он снимал видео, в котором раскрывал все проблемы с IPA, которые практически все учителя IPA делают онлайн, когда вдруг у него возникла блестящая идея: приложение! Приложение, в котором люди учатся писать, читать и говорить фонетический алфавит с различными акцентами! Теперь у него было не только лучший фонетический алфавит и лучшая причина для его изучения, но и идеальный способ его преподавания.",
      paragraph6: "С помощью ChatGPT он быстро создал прототип на HTML, CSS и JavaScript для веба, но понял, что это приложение также должно быть для мобильных устройств. Он провел некоторые исследования, решил создать его на React Native и отправился на поиски учителя React Native. Он нашел Сиддхарта, который был первым учителем, которого он встретил, способным построить все, что он хотел, и так родился True Phonetics."
    },
    zh: { // Chinese
      title: "真实语音故事",
      paragraph1: "真实语音应用的开发始于2024年5月10日，当 澳大利亚多语言者亚历克斯·佩曼雇佣了印度编程教师西达特·比什特来帮助他实现完美学习发音的想法。最终，西达特相信这个应用程序将以一种前所未有的方式为人们的生活带来真正的价值，因此会成功。此时，他已经是一位经验丰富的全栈跨平台开发者，曾帮助启动过许多初创公司。因此，当亚历克斯提议他们停止作为学生和教师的身份，成为一家科技公司的创始人时，西达特欣然接受了。",
      paragraph2: "True Phonetics Pty. Ltd. 于2024年7月5日作为一家澳大利亚公司成立，西达特·比什特担任首席技术官，亚历克斯·佩曼担任首席执行官，但其真正的起源可以追溯到2019年，当时亚历克斯开始教授国际音标（IPA）给他的英语学生。随着时间的推移，他在阅读IPA以及阅读和书写他修改过的IPA版本方面变得完全流利，最终这个版本被称为“新音标模型”。亚历克斯必须修改IPA，以便用不同的口音音标写出数百页的内容。这是必要的，因为普通的IPA在大规模生产音标文本时过于不准确。相比之下，他开发的NPM在描述亚历克斯说英语的方式时是100%准确的，尽管它的可读性和逻辑性远不如它本可以做到的。",
      paragraph3: "除了简化音标字母表外，亚历克斯还以许多人无法理解的方式理解了它的价值。他在学习外语时已经理解了音标字母表的价值，因为他自学了法语音标，并亲身体验了人类大脑如何比原始声音更好地理解和记忆图像。因此，当你知道与某个声音相关的图像时，你可以在脑海中建立对该声音的理解和意识，使你能够更好地听到它，并且如果你练习，就能更好地发出它。此外，亚历克斯理解到，作为一名英语使用者，英语IPA对他有价值，因为它允许人们书写口音。通过研究和玩弄声音，他意识到用不同的英语口音说话是多么简单，而无需发出任何新声音；只需在不同的地方发出与平常相同的声音。",
      paragraph4: "在已经学会说法语、西班牙语、意大利语、德语和葡萄牙语并至少能进行日常对话后，亚历克斯将他的语言学习技巧应用于学习用不同口音说英语。亚历克斯作为多语言者成功的原因之一是他在自言自语时没有自我意识。正如他通过对已知单词应用不同的发音模式学会了很多葡萄牙语一样，亚历克斯应用发音模式来实现不同的口音，并练习直到流利。",
      paragraph5: "亚历克斯在他异常先进的音标知识和能力上花费了多年时间。然后，在2024年5月初，他正在制作一段视频，揭示几乎所有IPA教师在线上所犯的IPA问题，突然他灵光一现：一个应用程序！一个让人们学习用不同口音书写、阅读和说音标的应用程序！现在，他不仅拥有最好的音标字母表和学习它的最佳理由，还有教授它的完美方式。",
      paragraph6: "在ChatGPT的帮助下，他迅速用HTML、CSS和JavaScript为网络构建了一个原型，但他意识到这个应用程序也需要适用于移动设备。他进行了一些研究，决定用React Native构建它，并开始寻找React Native教师。他找到了西达特，他是他遇到的第一个能够构建任何他想要的东西的教师，于是真实语音应运而生。"
    },
    ja: { // Japanese
      title: "真の音声学の物語",
      paragraph1: "真の音声学アプリの開発は、2024年5月10日にオーストラリアのポリグロット、アレックス・ペンマンがインドのコーディング教師、シッダールト・ビシュトを雇い、発音を学ぶための完璧な方法のアイデアを実現する手助けを依頼したことから始まりました。最終的に、シッダールトはこのアプリが人々の生活に前例のない方法で本当の価値をもたらすと信じるようになり、成功するだろうと考えました。この時点で、彼はすでに多くのスタートアップを立ち上げた経験豊富なフルスタック、クロスプラットフォームの開発者でした。したがって、アレックスが学生と教師の立場をやめてテクノロジー企業の創業者になることを提案したとき、シッダールトは喜んで受け入れました。",
      paragraph2: "True Phonetics Pty. Ltd.は、2024年7月5日にオーストラリアの会社として設立され、シッダールト・ビシュトがCTO、アレックス・ペンマンがCEOを務めましたが、その真の起源は2019年にさかのぼります。アレックスは英語の学生に国際音声記号（IPA）を教え始めました。時が経つにつれて、彼はIPAを読むこと、そして彼が修正したIPAのバージョンを読み書きすることに完全に流暢になりました。このバージョンは最終的に「新音声モデル」と呼ばれることになります。アレックスは、異なるアクセントで数百ページを音声的に書くためにIPAを修正する必要がありました。通常のIPAは音声テキストの大量生産に使用するにはあまりにも不正確だったため、これは必要でした。対照的に、彼が開発したNPMは、アレックスが英語を話す方法を100%正確に記述していましたが、可読性や論理性はそれが可能であったかもしれないものよりもはるかに劣っていました。",
      paragraph3: "音声アルファベットを簡素化するだけでなく、アレックスは多くの人が理解していない方法でその価値を理解していました。彼は外国語を学ぶ際に音声アルファベットの価値をすでに理解しており、フランス語の音声アルファベットを独学し、無生音よりも画像をよりよく理解し記憶できる人間の心の働きを直接体験しました。したがって、音に関連する画像を知っていると、その音に対する理解と意識を心の中に構築できるため、よりよく聞き取ることができ、練習すればより良く発音できるようになります。さらに、アレックスは、英語のIPAが英語を話す彼にとって価値があることを理解していました。なぜなら、それはアクセントを書くことを可能にするからです。研究や音を使った遊びを通じて、彼は新しい音を作ることなく異なる英語のアクセントで話すことがどれほど簡単であるかを認識しました。いつもの音を出すだけで、異なる場所で行うことができるのです。",
      paragraph4: "フランス語、スペイン語、イタリア語、ドイツ語、ポルトガル語を少なくとも会話レベルで話せるようになったアレックスは、異なるアクセントで英語を話すために彼の言語学習技術を応用しました。アレックスがポリグロットとして成功した理由の一つは、自分自身に大声で話すことに対する自己意識がなかったことです。彼はすでに知っている単語に異なる発音パターンを適用することで多くのポルトガル語を話すことを学んだように、アレックスは異なるアクセントを達成するため に発音パターンを適用し、流暢さを得るまで練習しました。",
      paragraph5: "アレックスは、彼の異常に進んだ音声知識と能力に何年も費やしました。そして、2024年5月の初めに、彼はほぼすべてのIPA教師がオンラインで行うIPAの問題を暴露するビデオを作成しているときに、突然ひらめきました：アプリ！人々が異なるアクセントで音声アルファベットを読み書きし、話すことを学ぶアプリ！今、彼は最高の音声アルファベットとそれを学ぶための最高の理由を持っているだけでなく、それを教えるための完璧な方法も持っていました。",
      paragraph6: "ChatGPTの助けを借りて、彼はすぐにHTML、CSS、JavaScriptでウェブ用のプロトタイプを構築しましたが、このアプリはモバイル用でも必要だと気づきました。彼は調査を行い、React Nativeで構築することを決定し、React Nativeの教師を探し始めました。彼はシッダールトを見つけました。彼は彼が出会った最初の教師で、彼が望むものを何でも構築できる人でした。そして、True Phoneticsが誕生しました。"
    },
    ko: { // Korean
      title: "진정한 음성학 이야기",
      paragraph1: "진정한 음성학 앱의 개발은 2024년 5월 10일에 호주 다국어 구사자 알렉스 펜맨이 인도 코딩 교사 시다르트 비쉬트를 고용하여 발음을 배우는 완벽한 방법에 대한 아이디어를 실현하는 데 도움을 요청하면서 시작되었습니다. 결국 시다르트는 이 앱이 사람들의 삶에 전례 없는 방식으로 진정한 가치를 가져다줄 것이라고 믿게 되었고, 따라서 성공할 것이라고 생각했습니다. 이 시점에서 그는 이미 많은 스타트업을 시작하는 데 도움을 준 경험이 풍부한 풀스택 크로스 플랫폼 개발자였습니다. 따라서 알렉스가 학생과 교사의 역할을 중단하고 기술 회사의 창립자가 되자고 제안했을 때, 시다르트는 기꺼이 수락했습니다.",
      paragraph2: "True Phonetics Pty. Ltd.는 2024년 7월 5일 호주 회사로 설립되었으며, 시다르트 비쉬트가 CTO, 알렉스 펜맨이 CEO로 재직하고 있지만, 그 진정한 기원은 2019년으로 거슬러 올라갑니다. 알렉스는 영어 학생들에게 국제 음성 기호(IPA)를 가르치기 시작했습니다. 시간이 지나면서 그는 IPA를 읽고, 수정한 IPA 버전을 읽고 쓰는 데 완전히 유창해졌습니다. 이 버전은 결국 '신 음성 모델'이라고 불리게 됩니다. 알렉스는 다양한 억양으로 수백 페이지를 음성적으로 쓰기 위해 IPA를 수정해야 했습니다. 일반 IPA는 음성 텍스트의 대량 생산에 사용하기에는 너무 부정확했기 때문에 필요했습니다. 반면 그가 개발한 NPM은 알렉스가 영어를 말하는 방식을 100% 정확하게 설명했지만, 가독성과 논리성은 그럴 수 있었던 것보다 훨씬 떨어졌습니다.",
      paragraph3: "음성 알파벳을 단순화하는 것 외에도 알렉스는 많은 사람들이 이해하지 못하는 방식으로 그 가치를 이해했습니다. 그는 외국어를 배울 때 음성 알파벳의 가치를 이미 이해하고 있었으며, 프랑스어 음성 알파벳을 독학하며 인간의 마음이 원시 소리보다 이미지를 더 잘 이해하고 기억할 수 있다는 것을 직접 경험했습니다. 따라서 소리와 관련된 이미지를 알게 되면, 그 소리에 대한 이해와 인식을 마음속에 구축할 수 있어, 더 잘 들을 수 있고 연습하면 더 잘 발음할 수 있습니다. 또한 알렉스는 영어를 사용하는 그에게 영어 IPA가 가치가 있다는 것을 이해했습니다. 왜냐하면 그것이 억양을 쓸 수 있게 해주기 때문입니다. 연구와 소리 놀이를 통해 그는 새로운 소리를 만들지 않고도 다른 영어 억양으로 말하는 것이 얼마나 쉬운지를 깨달았습니다; 평소와 같은 소리를 내되, 다른 장소에서 내기만 하면 됩니다.",
      paragraph4: "프랑스어, 스페인어, 이탈리아어, 독일어, 포르투갈어를 최소한 대화 수준으로 말할 수 있게 된 알렉스는 다양한 억양으로 영어를 말하기 위해 그의 언어 학습 기술을 적용했습니다. 알렉스가 다국어 구사자로서 성공한 이유 중 하나는 자신에게 큰 소리로 말할 때 자의식이 없었다는 것입니다. 그가 이미 알고 있는 단어에 다양한 발음 패턴을 적용하여 많은 포르투갈어를 배우듯이, 알렉스는 다양한 억양을 달성하기 위해 발음 패턴을 적용하고 유창해질 때까지 연습했습니다.",
      paragraph5: "알렉스는 그의 비정상적으로 발전된 음성 지식과 능력에 수년을 보냈습니다. 그러다가 2024년 5월 초, 그는 거의 모든 IPA 교사가 온라인에서 하는 IPA 문제를 폭로하는 비디오를 만들고 있을 때 갑자기 번뜩이는 아이디어가 떠올랐습니다: 앱! 사람들이 다양한 억양으로 음성 알파벳을 쓰고 읽고 말하는 것을 배우는 앱! 이제 그는 최고의 음성 알파벳과 그것을 배울 최고의 이유를 가질 뿐만 아니라, 그것을 가르칠 완벽한 방법도 갖게 되었습니다.",
      paragraph6: "ChatGPT의 도움으로 그는 HTML, CSS 및 JavaScript로 웹용 프로토타입을 신속하게 구축했지만, 이 앱이 모바일에서도 필요하다는 것을 깨달았습니다. 그는 몇 가지 조사를 하고 React Native로 구축하기로 결정한 후 React Native 교사를 찾기 시작했습니다. 그는 시다르트를 찾았고, 그가 만난 첫 번째 교사로서 원하는 모든 것을 구축할 수 있는 사람이었습니다. 그리고 진정한 음성학이 탄생했습니다."
    },
    
    ur: { // Urdu
      title: "سچی صوتیات کی کہانی",
      paragraph1: "سچی صوتیات ایپ کی ترقی 10 مئی 2024 کو شروع ہوئی جب آسٹریلیائی پولیگلٹ الیکس پین مین نے بھارتی کوڈنگ استاد سدھارتھ بشٹ کو اپنے تلفظ سیکھنے کے بہترین طریقے کے خیال کو ترقی دینے میں مدد کرنے کے لیے بھرتی کیا۔ آخرکار، سدھارتھ کو یقین ہو گیا کہ یہ ایپ لوگوں کی زندگیوں میں حقیقی قیمت لائے گی جس طرح پہلے کبھی نہیں ہوا اور اس لیے یہ کامیاب ہوگی۔ اس وقت، وہ پہلے ہی ایک تجربہ کار فل اسٹیک، کراس پلیٹ فارم ڈویلپر تھا جس نے کئی اسٹارٹ اپس کو شروع کرنے میں مدد کی تھی۔ لہذا، جب الیکس نے تجویز دی کہ وہ طالب علم اور استاد بننا بند کریں اور ایک ٹیکنالوجی کمپنی کے بانی بنیں، تو سدھارتھ نے خوشی سے قبول کر لیا۔",
      paragraph2: "True Phonetics Pty. Ltd. 5 جولائی 2024 کو ایک آسٹریلیائی کمپنی کے طور پر قائم کی گئی، جس میں سدھارتھ بشٹ CTO اور الیکس پین مین CEO تھے، لیکن اس کی حقیقی شروعات 2019 میں ہوئی جب الیکس نے اپنے انگریزی زبان کے طلباء کو بین الاقوامی صوتی الفابیٹ (IPA) پڑھانا شروع کیا۔ وقت کے ساتھ، وہ IPA پڑھنے اور ایک ورژن کو پڑھنے اور لکھنے میں مکمل طور پر ماہر ہو گیا جسے اس نے تبدیل کیا تھا اور جسے آخرکار 'نیا صوتی ماڈل' کہا جائے گا۔ الیکس کو مختلف لہجوں میں صوتی طور پر سینکڑوں صفحات لکھنے کے لیے IPA کو تبدیل کرنا پڑا۔ یہ ضروری تھا کیونکہ عام IPA صوتی متون کی بڑے پیمانے پر پیداوار کے لیے بہت غیر درست تھا۔ اس کے برعکس، NPM جو اس نے تیار کیا تھا، وہ 100% درست تھا جو الیکس کے انگریزی بولنے کے طریقے کی وضاحت کرتا تھا، حالانکہ یہ پڑھنے میں بہت کم واضح اور منطقی تھا۔",
      paragraph3: "صوتی الفابیٹ کو آسان بنانے کے ساتھ ساتھ، الیکس نے اس کی قیمت کو بھی ایک ایسے طریقے سے سمجھا جو بہت سے لوگ نہیں سمجھتے۔ وہ پہلے ہی ایک غیر ملکی زبان سیکھتے وقت صوتی الفابیٹ کی قیمت کو سمجھتا تھا، کیونکہ اس نے خود کو فرانسیسی صوتی الفابیٹ سکھایا تھا اور یہ تجربہ کیا تھا کہ انسانی دماغ خام آوازوں کی نسبت تصاویر کو بہتر طور پر سمجھ اور یاد کر سکتا ہے۔ لہذا، جب آپ کسی آواز سے منسلک تصویر جانتے ہیں، تو آپ اپنے دماغ میں اس آواز کی سمجھ اور آگاہی بنا سکتے ہیں، جس سے آپ اسے بہتر سن سکتے ہیں اور اگر آپ مشق کریں تو اسے بہتر پیدا کر سکتے ہیں۔ مزید برآں، الیکس نے سمجھا کہ انگریزی IPA اس کے لیے ایک انگریزی بولنے والے کے طور پر قیمت رکھتا ہے کیونکہ یہ کسی کو لہجے لکھنے کی اجازت دیتا ہے۔ تحقیق اور آوازوں کے ساتھ کھیلنے کے ذریعے، اس نے یہ سمجھا کہ بغیر کسی نئے آوازیں پیدا کیے مختلف انگریزی لہجے میں بولنا کتنا آسان ہے؛ بس وہی آوازیں پیدا کرنا جو عام طور پر ہوتی ہیں، لیکن مختلف جگہوں پر۔",
      paragraph4: "فرانسیسی، ہسپانوی، اطالوی، جرمن، اور پرتگالی کو کم از کم گفتگو کی سہولت کے ساتھ بولنے کے بعد، الیکس نے مختلف لہجوں کے ساتھ انگریزی بولنے کے لیے اپنی زبان سیکھنے کی تکنیکوں کو اپنایا۔ الیکس کی ایک وجہ یہ تھی کہ وہ ایک پولیگلٹ کے طور پر اتنا کامیاب رہا کہ وہ خود سے بلند آواز میں بولنے میں خود آگاہی نہیں رکھتا تھا۔ جیسے اس نے پہلے سے جانے والے الفاظ پر مختلف تلفظ کے نمونوں کو لاگو کرکے بہت سارا پرتگالی بولنا سیکھا، الیکس نے مختلف لہجوں کو حاصل کرنے کے لیے تلفظ کے نمونوں کو لاگو کیا اور روانی تک مشق کی۔",
      paragraph5: "الیکس نے اپنے غیر معمولی طور پر ترقی یافتہ صوتی علم اور صلاحیت پر سال گزارے۔ پھر، مئی 2024 کے آغاز میں، وہ ایک ویڈیو بنا رہا تھا جس میں وہ IPA کے تمام مسائل کو اجاگر کر رہا تھا جو تقریباً تمام IPA اساتذہ آن لائن کرتے ہیں جب اچانک اسے ایک دماغی چمک ملی: ایک ایپ! ایک ایپ جس میں لوگ مختلف لہجوں میں صوتی الفابیٹ کو لکھنا، پڑھنا اور بولنا سیکھتے ہیں! اب، نہ صرف اس کے پاس بہترین صوتی الفابیٹ اور اسے سیکھنے کا بہترین سبب تھا، بلکہ اسے اسے سکھانے کا بہترین طریقہ بھی ملا۔",
      paragraph6: "ChatGPT کی مدد سے، اس نے جلدی سے HTML، CSS، اور JavaScript میں ویب کے لیے ایک پروٹوٹائپ بنایا، لیکن اسے احساس ہوا کہ یہ ایپ موبائل کے لیے بھی ہونی چاہیے۔ اس نے کچھ تحقیق کی، فیصلہ کیا کہ اسے React Native میں بنانا ہے، اور ایک React Native استاد کی تلاش میں نکل پڑا۔ اس نے سدھارتھ کو پایا، جو وہ پہلا استاد تھا جس سے وہ ملا جو اس کی خواہش کے مطابق کچھ بھی بنا سکتا تھا، اور اس طرح سچی صوتیات کا جنم ہوا۔"
    },
    id: { // Indonesian
      title: "Kisah True Phonetics",
      paragraph1: "Pengembangan aplikasi True Phonetics dimulai pada 10 Mei 2024 ketika poliglot Australia Alex Penman menyewa guru pemrograman India Siddharth Bisht untuk membantunya mengembangkan ide tentang cara sempurna untuk belajar pengucapan. Akhirnya, Siddharth mulai percaya bahwa aplikasi ini akan membawa nilai nyata ke dalam kehidupan orang-orang dengan cara yang belum pernah dilakukan sebelumnya dan oleh karena itu akan sukses. Pada saat itu, dia sudah menjadi pengembang full-stack dan lintas platform yang berpengalaman yang telah membantu meluncurkan banyak startup. Oleh karena itu, ketika Alex mengusulkan agar mereka berhenti menjadi siswa dan guru dan menjadi pendiri perusahaan teknologi, Siddharth dengan antusias menerimanya.",
      paragraph2: "True Phonetics Pty. Ltd. didirikan sebagai perusahaan Australia pada 5 Juli 2024 dengan Siddharth Bisht sebagai CTO dan Alex Penman sebagai CEO, tetapi asal-usulnya yang sebenarnya dapat ditelusuri kembali ke tahun 2019 ketika Alex mulai mengajarkan Alfabet Fonetik Internasional (IPA) kepada siswa bahasa Inggrisnya. Seiring waktu, dia menjadi sangat fasih dalam membaca IPA dan membaca serta menulis versi IPA yang telah dimodifikasinya dan yang akhirnya akan disebut 'Model Fonetik Baru'. Alex harus memodifikasi IPA untuk menulis ratusan halaman secara fonetik dalam berbagai aksen. Ini diperlukan karena IPA normal terlalu tidak akurat untuk digunakan dalam produksi massal teks fonetik. Sebaliknya, NPM yang dia kembangkan 100% akurat dalam menggambarkan cara Alex berbicara bahasa Inggris, meskipun jauh kurang terbaca dan logis daripada yang seharusnya.",
      paragraph3: "Selain menyederhanakan alfabet fonetik, Alex juga memahami nilainya dengan cara yang tidak dipahami banyak orang. Dia sudah memahami nilai alfabet fonetik saat belajar bahasa asing, karena dia telah mengajarkan dirinya sendiri alfabet fonetik Prancis dan mengalami secara langsung bagaimana pikiran manusia dapat menangkap dan mengingat gambar lebih baik daripada suara mentah. Oleh karena itu, ketika Anda mengetahui gambar yang terkait dengan suara, Anda dapat membangun pemahaman dan kesadaran tentang suara itu dalam pikiran Anda, memungkinkan Anda untuk mendengarnya lebih baik dan, jika Anda berlatih, memproduksinya dengan lebih baik. Selain itu, Alex memahami bahwa IPA bahasa Inggris memiliki nilai baginya sebagai penutur bahasa Inggris karena memungkinkan seseorang untuk menulis aksen. Melalui penelitian dan bermain dengan suara, dia menyadari betapa mudahnya berbicara dengan aksen Inggris yang berbeda tanpa membuat suara baru; hanya dengan membuat suara yang sama seperti biasa, tetapi di tempat yang berbeda.",
      paragraph4: "Setelah belajar berbicara dalam bahasa Prancis, Spanyol, Italia, Jerman, dan Portugis setidaknya dengan mudah dalam percakapan, Alex menerapkan teknik pembelajaran bahasanya untuk belajar berbicara bahasa Inggris dengan berbagai aksen. Salah satu alasan mengapa Alex sangat sukses sebagai poliglot adalah karena dia tidak merasa canggung saat berbicara dengan dirinya sendiri. Sama seperti dia belajar berbicara banyak bahasa Portugis hanya dengan menerapkan pola pengucapan yang berbeda pada kata-kata yang sudah dia ketahui, Alex menerapkan pola pengucapan untuk mencapai berbagai aksen dan berlatih hingga fasih.",
      paragraph5: "Alex menghabiskan bertahun-tahun duduk di atas pengetahuan dan kemampuannya yang sangat maju dalam fonetik. Kemudian, pada awal Mei 2024, dia sedang membuat video yang mengungkap semua masalah dengan IPA yang hampir semua pengajar IPA lakukan secara online ketika tiba-tiba dia mendapatkan ide cemerlang: sebuah aplikasi! Sebuah aplikasi di mana orang belajar menulis, membaca, dan berbicara alfabet fonetik dalam berbagai aksen! Sekarang, dia tidak hanya memiliki alfabet fonetik terbaik dan alasan terbaik untuk mempelajarinya, tetapi dia juga memiliki cara sempurna untuk mengajarkannya.",
      paragraph6: "Dengan bantuan ChatGPT, dia dengan cepat membangun prototipe dalam HTML, CSS, dan JavaScript untuk web, tetapi dia menyadari bahwa aplikasi ini juga perlu untuk perangkat seluler. Dia melakukan beberapa penelitian, memutuskan untuk membangunnya di React Native, dan mencari guru React Native. Dia menemukan Siddharth, yang merupakan guru pertama yang dia temui yang bisa membangun apa pun yang dia inginkan, dan dengan demikian True Phonetics lahir."
    }
  
  };

  export default Translations;