//themes.utils.js

export const themes = {
  classic: {
    headerBg: "#bdd8dd",
    playbuttonColor: "#7adaf5",
    keyboardKey: "#f9e3d2",
    buttonColor: "#0e7490",
    disabledButtonColor: "#a0c1ca",
    buttonText: "#fff",
    textColor: "#000",
    headerNoticeText: "#fff",
    headerNoticeBg: "#bdd8dd50",
    quizContainer: "#9fc1ca",
    questionBox: "#bdd8dd",
    selectedOptionButton: "#6fe3f2",
    unSelectedOptionButton: "#badce8",
    iconColor: "#fff",
    floatMenuBg: "#edf3f5",
    floatMenuBgHover: "#00bcd4", // Proper hover background
    floatMenuText: "#000", // Changed to black for better contrast
    floatMenuBorder: "#fff",
    settingsBg: "#e5f4f7",
    backgroundColor: "#a0c1ca",
    headerTextColor: "#0e7490", // Black for headers
    mainTextColor: "#000", // Black for main text
    placeholderBg: "#f0f0f0",
    headingTextColor: "#0097A7",
    containerColor:"#e0f2f1",
    innerContainerColor:"#83e1f2",
    correctInnerBg:"#d3f0d6",
    correctBgOuter:"#96e69e",
    correctTextColor:"#02B875",
    grayText:"#757575",
    incorrectInnerBg: "#f8d7da", // Light red background
    incorrectBgOuter: "#f5c6cb", // Medium red background
    incorrectTextColor: "#9e2430" // Dark red text color
  },
  neon: {
    backgroundColor: "#111122",
    borderColor: "#3e3e5c",
    headerBg: "#222244",
    playbuttonColor: "#ff4d88",
    keyboardKey: "#5e5ea6",
    buttonColor: "#ff4d88",
    disabledButtonColor: "#3e3e5c",
    textColor: "#fff",
    quizContainer: "#141438",
    questionBox: "#3e3e4f",
    selectedOptionButton: "#7c4dff",
    unSelectedOptionButton: "#4d4d72",
    iconColor: "#fff",
    settingsBg: "#2b2b3c",
    headerNoticeText: "#fff",
    floatMenuBg: "#3e3e5c", // Added background for float menu
    floatMenuBgHover: "#ff4d88", // Neon hover color
    floatMenuText: "#fff", // White text
    floatMenuBorder: "#ff4d88",
    headerTextColor: "#fff", // White for headers
    mainTextColor: "#fff",
    placeholderBg: "#222244",
    headingTextColor: "#ff4d88",
    containerColor:"#2b2b3c",
    innerContainerColor:"#323259",
    correctInnerBg:"#004D40",
    correctBgOuter:"#002922",
    correctTextColor:"#02B875",
    grayText:"#E0E0E0",
    incorrectInnerBg: "#7A0000", // Dark red for inner background
    incorrectBgOuter: "#450101", // Even darker red for outer background
    incorrectTextColor: "#9e2430" 

  },
  pastel: {
    backgroundColor: "#fef6f0",
    borderColor: "#f8e1dc",
    headerBg: "#fce1e1",
    playbuttonColor: "#faa198",
    keyboardKey: "#fcf7f7",
    buttonColor: "#ff6f61",
    disabledButtonColor: "#f58e84",
    textColor: "#2c3e50",
    quizContainer: "#faf3f2",
    questionBox: "#f1d0c1",
    selectedOptionButton: "#f7948b",
    unSelectedOptionButton: "#faf3f2",
    settingsBg: "#ffece5",
    headerNoticeText: "#2c3e50",
    floatMenuBg: "#fbe4e1", // Added pastel background
    floatMenuBgHover: "#ff6f61", // Consistent hover color
    floatMenuText: "#2c3e50", // Dark text
    floatMenuBorder: "#f8e1dc",
    headerTextColor: "#2c3e50",
    mainTextColor: "#2c3e50",
    placeholderBg: "#fff",
    headingTextColor: "#ff6f61",
    containerColor:"#f8e1dc",
    innerContainerColor:"#ffebe3",
    correctInnerBg:"#d3f0d6",
    correctBgOuter:"#96e69e",
    correctTextColor:"#02B875",
    grayText:"#757575",
    incorrectInnerBg: "#f8d7da", // Light red background
    incorrectBgOuter: "#f5c6cb", // Medium red background
    incorrectTextColor: "#9e2430" // Dark red text color
  },
  lit: {
    backgroundVideo: null,
    backgroundColor: "#0b0703",
    headerBg: "#f3e7c3",
    playbuttonColor: "#ffc878",
    keyboardKey: "#f7efd8",
    headerColor: "#f3e7c3",
    buttonColor: "#2a1c0f",
    disabledButtonColor: "#cdbf98",
    textColor: "#2a1c0f",
    quizContainer: "#f3e7c3",
    questionBox: "#f3e7c3",
    selectedOptionButton: "#2a1c0f",
    unSelectedOptionButton: "#e6d3a3",
    settingsBg: "#f7efd8",
    headerNoticeText: "#2a1c0f",
    floatMenuBg: "#f3e7c3",
    floatMenuBgHover: "#ffc878",
    floatMenuText: "#2a1c0f",
    floatMenuBorder: "#b67b2c",
    headerTextColor: "#2a1c0f",
    mainTextColor: "#2a1c0f",
    placeholderBg: "#f7efd8",
    headingTextColor: "#2a1c0f",
    containerColor:"#f3e7c3",
    innerContainerColor:"#f7efd8",
    correctInnerBg:"#d3f0d6",
    correctBgOuter:"#96e69e",
    correctTextColor:"#02B875",
    grayText:"#5a4030",
    incorrectInnerBg: "#f8d7da",
    incorrectBgOuter: "#f5c6cb",
    incorrectTextColor: "#9e2430"
  },
  ttv: {
    backgroundVideo: null,
    backgroundColor: "#070b16",
    headerBg: "#0b1220",
    playbuttonColor: "#22d3ee",
    keyboardKey: "#111b30",
    headerColor: "#0b1220",
    buttonColor: "#22d3ee",
    disabledButtonColor: "#1f2937",
    textColor: "#e2e8f0",
    quizContainer: "#0f172a",
    questionBox: "#111b30",
    selectedOptionButton: "#22d3ee",
    unSelectedOptionButton: "#16233f",
    settingsBg: "#0f172a",
    headerNoticeText: "#e2e8f0",
    floatMenuBg: "#0f172a",
    floatMenuBgHover: "#22d3ee",
    floatMenuText: "#e2e8f0",
    floatMenuBorder: "#1f2937",
    headerTextColor: "#e2e8f0",
    mainTextColor: "#e2e8f0",
    placeholderBg: "#0b1220",
    headingTextColor: "#22d3ee",
    containerColor:"#0f172a",
    innerContainerColor:"#111b30",
    correctInnerBg:"#163c2c",
    correctBgOuter:"#0f2e24",
    correctTextColor:"#34d399",
    grayText:"#94a3b8",
    incorrectInnerBg: "#3f1d2e",
    incorrectBgOuter: "#2a1321",
    incorrectTextColor: "#fca5a5"
  },
  eag: {
    backgroundVideo: null,
    backgroundColor: "#040a12",
    borderColor: "#1f3a52",
    headerBg: "#0b1724",
    playbuttonColor: "#f3b046",
    keyboardKey: "#13283a",
    buttonColor: "#f3b046",
    disabledButtonColor: "#2a3f54",
    textColor: "#e8f0fb",
    quizContainer: "#0f2435",
    questionBox: "#132f42",
    selectedOptionButton: "#1c3d57",
    unSelectedOptionButton: "#0f2435",
    settingsBg: "#0f2435",
    headerNoticeText: "#d5e3f5",
    floatMenuBg: "#0f2435",
    floatMenuBgHover: "#1c3d57",
    floatMenuText: "#e8f0fb",
    floatMenuBorder: "#1f3a52",
    headerTextColor: "#f3b046",
    mainTextColor: "#e8f0fb",
    placeholderBg: "#0b1724",
    headingTextColor: "#f3b046",
    containerColor:"#0f2435",
    innerContainerColor:"#132f42",
    correctInnerBg:"#123524",
    correctBgOuter:"#0c2319",
    correctTextColor:"#6ee7b7",
    grayText:"#9db5d3",
    incorrectInnerBg: "#33161f",
    incorrectBgOuter: "#1f0f14",
    incorrectTextColor: "#fda4af"
  },
  sunset: {
    backgroundColor: "#ffefd5",
    borderColor: "#ff4500",
    headerBg: "#fcbda4",
    playbuttonColor: "#f79d8d",
    keyboardKey: "#fae8e1",
    buttonColor: "#ff6347",
    disabledButtonColor: "#ff9900",
    textColor: "#8b4513",
    quizContainer: "#ffdab9",
    questionBox: "#fcbda4",
    selectedOptionButton: "#ff8254",
    unSelectedOptionButton: "#f0d2c7",
    settingsBg: "#ffe8d6",
    headerNoticeText: "#8b4513",
    floatMenuBg: "#ffdab9", // Sunset float menu background
    floatMenuBgHover: "#ff4500", // Contrasting hover color
    floatMenuText: "#8b4513", // Sunset text color
    floatMenuBorder: "#8b4513",
    headerTextColor: "#8b4513",
    mainTextColor: "#8b4513",
    placeholderBg: "#fff",
    headingTextColor: "#ff6347",
    containerColor:"#ffe8d6",
    innerContainerColor:"#fac8b4",
    correctInnerBg:"#d3f0d6",
    correctBgOuter:"#96e69e",
    correctTextColor:"#02B875",
    grayText:"#757575",
    incorrectInnerBg: "#f8d7da", // Light red background
    incorrectBgOuter: "#f5c6cb", // Medium red background
    incorrectTextColor: "#9e2430" // Dark red text color
  },
};
